clc
clear
format

syms m I_x I_z I_xz g ...
    ro V_0 S b ...
    m_dot I_x_dot I_z_dot I_xz_dot ...
    Y_dot_v L_dot_v N_dot_v ...
    Y_dot_p L_dot_p N_dot_p ...
    Y_dot_r L_dot_r N_dot_r ...
    Y_dot_ksi L_dot_ksi N_dot_ksi ...
    Y_dot_dzeta L_dot_dzeta N_dot_dzeta ...
    W_e U_e theta_e...
;

m_dot =  m / (1/2 * ro * V_0 * S);
I_x_dot =  I_x / (1/2 * ro * V_0 * S * b);
I_z_dot =  I_z / (1/2 * ro * V_0 * S * b);
I_xz_dot =  I_xz / (1/2 * ro * V_0 * S * b);

U_e = V_0 * cos(theta_e);
W_e = V_0 * sin(theta_e);



M = [m_dot, 0, 0, 0, 0; ...
    0, I_x_dot, -I_xz_dot, 0, 0; ...
    0, -I_xz_dot, I_z_dot, 0, 0;...
    0,0,0,1,0;
    0,0,0,0,1;];

A_prim = ...
    [Y_dot_v, Y_dot_p * b + m_dot*W_e, Y_dot_r * b - m_dot*U_e, m_dot * g * cos(theta_e), m_dot * g * sin(theta_e);...
    L_dot_v, L_dot_p * b, L_dot_r * b, 0, 0;...
    N_dot_v, N_dot_p * b, N_dot_r * b, 0, 0;...
    0, 1, 0, 0, 0;...
    0, 0, 1, 0, 0];

B_prim = ...
    [V_0 * Y_dot_ksi, V_0 * Y_dot_dzeta;...
    V_0 * L_dot_ksi, V_0 * L_dot_dzeta;...
    V_0 * N_dot_ksi, V_0 * N_dot_dzeta;...
    0, 0;
    0, 0;];

A = simplify(M^(-1) * A_prim);
B = simplify(M^(-1) * B_prim);
