syms m I_y g ...
    X_dot_u Z_dot_u M_dot_u ...
    X_dot_w Z_dot_w M_dot_w ...
    X_dot_w_dot Z_dot_w_dot M_dot_w_dot ...
    X_dot_q Z_dot_q M_dot_q ...
    X_dot_ni Z_dot_ni M_dot_ni ...
    X_dot_tau Z_dot_tau M_dot_tau ...
    W_e U_e theta_e...
;

M = [m, -X_dot_w_dot, 0, 0;...
    0, m-Z_dot_w_dot, 0, 0;...
    0, -M_dot_w_dot, I_y, 0;...
    0,0,0,1];

A_prim = ...
    [X_dot_u, X_dot_w, X_dot_q - m * W_e, -m * g * cos(theta_e);...
    Z_dot_u, Z_dot_w, Z_dot_q + m * U_e, -m * g * sin(theta_e);...
    M_dot_u, M_dot_w, M_dot_q, 0;...
    0,0,1,0];
A = M^(-1) * A_prim
