new_A_longitudinal = [a_longitudinal(1,1:4),;...
                    a_longitudinal(1,5:8);...
                    a_longitudinal(1,9:12);...
                    a_longitudinal(1,13:16)];
new_B_longitudinal = [b_longitudinal(1,1:2);...
                    b_longitudinal(1,3:4);...
                    b_longitudinal(1,5:6);...
                    b_longitudinal(1,7:8)];


new_A_lateral = [a_lateral(1,1:5);...
        a_lateral(1,6:10);...
        a_lateral(1,11:15);...
        a_lateral(1,16:20);...
        a_lateral(1,21:25)];
new_B_lateral = [b_lateral(1,1:2); b_lateral(1,3:4); b_lateral(1,5:6); b_lateral(1,7:8); b_lateral(1,9:10)];

if(exist(strcat('../../AppOutput/', num2str(client_id), '.mat'), 'file') == 2) % if workspace exists
    load(strcat('../../AppOutput/', num2str(client_id)));
    aircraft.AddStrategy(new_A_longitudinal, new_B_longitudinal,...
                                    new_A_lateral, new_B_lateral);
    aircraft.previous_result.StrategiesResults = [ aircraft.previous_result.StrategiesResults, aircraft.previous_result.StrategiesResults(1)];
else % if workspace does not exist - simulation_step_from_fixed_update, simulation_time_from_AircraftStrategy_cs from Workspace_Initializator
    aircraft = Aircraft(new_A_longitudinal, new_B_longitudinal,...
                    new_A_lateral, new_B_lateral,...
                    simulation_step_from_fixed_update, simulation_time_from_AircraftStrategy_cs);
end

%% Workspace saver
clearvars -except aircraft client_id;
save(strcat('../../AppOutput/', num2str(client_id)));
clear;